//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Posts = new HashSet<Post>();
            this.Threads = new HashSet<Thread>();
            this.Warnings = new HashSet<Warning>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public byte[] Hash { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> RemovalDate { get; set; }
        public string Location { get; set; }
        public Nullable<int> AvatarId { get; set; }
        public bool IsAdministrator { get; set; }
        public int NumberOfWarnings { get; set; }
        public bool IsBanned { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Avatar Avatar { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
        public virtual ICollection<Warning> Warnings { get; set; }
    }
}
