//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Threads
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> WhenAddedLastPost { get; set; }
        public string WhoAddedLastPost { get; set; }
        public Nullable<int> PostsNumber { get; set; }
        public string LastPost { get; set; }
    }
}
