//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForumDBContext : DbContext
    {
        public ForumDBContext()
            : base("name=ForumDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public virtual DbSet<Avatar> Avatars { get; set; }
        //public virtual DbSet<User> Users { get; set; }
        //public virtual DbSet<Category> Categories { get; set; }
        //public virtual DbSet<Post> Posts { get; set; }
        //public virtual DbSet<Thread> Threads { get; set; }
        //public virtual DbSet<V_Categories> V_Categories { get; set; }
        //public virtual DbSet<V_Threads> V_Threads { get; set; }
    }
}
