//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Warnings = new HashSet<Warning>();
        }
    
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public string PostContent { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ThreadId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Thread Thread { get; set; }
        public virtual ICollection<Warning> Warnings { get; set; }
    }
}
